package com.ngapp.metanmobile.composeapp

import com.ngapp.metanmobile.core.analytics.AnalyticsHelper
import com.ngapp.metanmobile.core.analytics.NoOpAnalyticsHelper
import com.ngapp.metanmobile.composeapp.di.mainModule
import com.ngapp.metanmobile.core.data.di.locationDataModule
import com.ngapp.metanmobile.core.data.di.syncDataModule
import com.ngapp.metanmobile.core.data.di.userDataModule
import com.ngapp.metanmobile.core.data.sync.DataSyncCoordinator
import com.ngapp.metanmobile.core.domain.sync.SyncManager
import com.ngapp.metanmobile.core.ui.ads.NativeAdsBridge
import com.ngapp.metanmobile.core.ui.ads.registerNativeAdsBridge
import com.ngapp.metanmobile.sync.di.iosSyncModule
import com.ngapp.metanmobile.sync.schedulers.registerBackgroundSync
import com.ngapp.metanmobile.core.datastore.di.userPreferencesDataStoreModule
import com.ngapp.metanmobile.core.database.di.databaseModule
import com.ngapp.metanmobile.core.network.client.di.networkClientModule
import com.ngapp.metanmobile.core.network.di.sharedNetworkModule
import com.ngapp.metanmobile.core.ui.di.uiModule
import com.ngapp.metanmobile.feature.onboarding.di.featureOnboardingModule
import com.ngapp.metanmobile.feature.news.di.featureNewsModule
import com.ngapp.metanmobile.feature.favorites.di.featureFavoritesModule
import com.ngapp.metanmobile.feature.home.di.featureHomeModule
import com.ngapp.metanmobile.feature.stationdetail.di.featureStationDetailModule
import com.ngapp.metanmobile.feature.cabinet.di.featureCabinetModule
import com.ngapp.metanmobile.feature.stations.di.featureStationsModule
import com.ngapp.metanmobile.feature.menu.di.featureMenuModule
import com.ngapp.metanmobile.feature.about.di.featureAboutModule
import com.ngapp.metanmobile.feature.careers.di.featureCareersModule
import com.ngapp.metanmobile.feature.contacts.di.featureContactsModule
import com.ngapp.metanmobile.feature.faq.di.featureFaqModule
import com.ngapp.metanmobile.feature.privacypolicy.di.featurePrivacyPolicyModule
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import org.koin.core.context.startKoin
import org.koin.dsl.module
import com.ngapp.metanmobile.widget.nearest.station.di.nearestStationWidgetModule
import com.ngapp.metanmobile.widget.core.di.widgetCoreModule
import com.ngapp.metanmobile.widget.core.WidgetReloader
import com.ngapp.metanmobile.widget.core.WidgetPublisher
import com.ngapp.metanmobile.core.data.di.widgetDataModule

/**
 * Initializes the shared graph before the SwiftUI host creates Compose content.
 *
 * @param nativeAdsBridge Swift's real GoogleMobileAds/UserMessagingPlatform implementation
 *   (MobileAdsBridge.swift) - see core:ui's NativeAdsBridge.kt for why this can't just be
 *   resolved through Koin like everything else here.
 * @param widgetReloader Swift's WidgetCenter call (WidgetReloaderBridge.swift), used to redraw
 *   the home-screen widgets after their data in the App Group changed.
 */
fun initSharedKoin(nativeAdsBridge: NativeAdsBridge, widgetReloader: WidgetReloader) {
    registerNativeAdsBridge(nativeAdsBridge)
    configureImageLoader()
    val koinApp = startKoin {
        modules(
            userPreferencesDataStoreModule(),
            databaseModule(),
            // "https://metan.by/" is the marketing website, not the JSON API — Android reads the
            // real API host from BuildConfig.METAN_ECOGAS_API (generated by the secrets-gradle-
            // plugin from secrets.properties' METAN_ECOGAS_API). There's no iOS equivalent of
            // that plugin, so it's hardcoded here instead; keep in sync with secrets.properties
            // if that Worker's URL ever changes. Using metan.by here was why every repository
            // except GithubUserRepository (a genuinely different host, api.github.com) 404'd —
            // the sync mechanism itself was working, just pointed at the wrong API host.
            networkClientModule(
                baseUrl = "https://metan-ecogas-api.ngapps-developer.workers.dev/",
                githubBaseUrl = "https://api.github.com/",
            ),
            sharedNetworkModule(),
            module { single<AnalyticsHelper> { NoOpAnalyticsHelper() } },
            userDataModule(),
            locationDataModule,
            // IosSyncManager drives the shared DataSyncCoordinator for foreground/launch-time
            // sync (same repositories, same retry-until-success policy as Android's SyncWorker);
            // registerBackgroundSync() below is iOS's actual WorkManager analog — a real
            // BGTaskScheduler registration, not just an in-process approximation.
            syncDataModule,
            iosSyncModule,
            mainModule,
            uiModule,
            featureOnboardingModule,
            featureNewsModule,
            featureFavoritesModule,
            featureHomeModule,
            featureStationDetailModule,
            featureCabinetModule,
            featureStationsModule,
            featureMenuModule,
            featureAboutModule,
            featureCareersModule,
            featureContactsModule,
            featureFaqModule,
            featurePrivacyPolicyModule,
            module { single<WidgetReloader> { widgetReloader } },
            widgetDataModule,
            widgetCoreModule,
            nearestStationWidgetModule,
        )
    }
    // Mirrors Android's Sync.initialize(context) call right after startKoin{} in
    // MetanMobileApplication.onCreate() — same "sync once at app launch" behavior, just reached
    // through the SyncManager Koin already built instead of going straight to WorkManager.
    koinApp.koin.get<SyncManager>().requestSync()
    // Mirrors Android's Widgets.initialize(): keeps the widgets' App Group data in step with the
    // local database for as long as the app runs (foreground or a background sync).
    koinApp.koin.get<WidgetPublisher>().start(CoroutineScope(SupervisorJob() + Dispatchers.Default))
    // BGTaskScheduler.registerForTaskWithIdentifier must run before the end of App.init() (this
    // SwiftUI app has no AppDelegate, so init() is the equivalent of applicationDidFinishLaunching)
    // — initSharedKoin() is called from exactly there (MetanMobileApp.swift), so this is the
    // right/only place for it.
    registerBackgroundSync(
        dataSyncCoordinator = koinApp.koin.get<DataSyncCoordinator>(),
        scope = CoroutineScope(SupervisorJob() + Dispatchers.Default),
    )
}
